### ISSUE TITLE
Definição campos calendário

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/calendario#13]
@diemello, precisamos conversar com o Ederson para definirmos quais campos farão parte do calendário.
* id (obrigatório para o componente)
* título (obrigatório para o componente)
* url (obrigatório para o componente)
* classe (obrigatório para o componente)
* início (obrigatório para o componente)
* fim (obrigatório para o componente)
* setor 
* pessoa
* local
* descrição
Acredito que estes já são suficientes, mas preciso de um OK de vocês.

**Comment by edersoncosta** [comment]
@aleodoni pelo que verifiquei no uso da ferramenta do Google Agenda é somente isso, pois já estamos incluindo a URL como adicional, mas contamos com a @Ebianca para dar um parecer pelo DAC. @diemello Alguma observação?

**Comment by edersoncosta** [comment]
@aleodoni Sobre a exibição, inicia-se sempre pela semana, caso seja desejo do usuário e seleciona o mês. Alguma objeção @Ebianca ?

**Comment by aleodoni** [comment]
Fico no aguardo do OK para prosseguirmos.

**Comment by Ebianca** [comment]
@aleodoni acerca dos itens segue dúvidas e considerações:  id,  título (título do Evento), url (esse também tinha na agenda, colocamos o link da pauta),  classe (seria um tipo? Reunião, Audiência, outros?)  início (Data e Hora), fim ((Data e Hora),  setor (comissão?),  pessoa (pessoa que incluiu?) local (se possível uma lista de possíveis locais e outros-poder incluir se for visita externa, por exemplo).
Acredito ser importante mais um campo, com a descrição completa para visualização ao selecionar o evento. modelo anexo. 
![modelo descricao](https://user-images.githubusercontent.com/40066179/41177122-4775be00-6b39-11e8-9af5-bfb459e24261.png)

**Comment by Ebianca** [comment]
@edersoncosta sobre a visualização padrão pode alterar para mensal, caso o calendário não fique muito pequeno, permitindo alterar a visualização para semanal ou a lista.

**Comment by aleodoni** [comment]
@Ebianca, em relação às colocações : 

* classe é usada para diferenciar visualmente os tipos de evento; quando disponibilizarmos a tela para visualização do calendário ficará mais claro.
* setor e pessoa : imaginamos que posteriormente, outros setores utilizarão o calendário, então criamos estes dois campos para podermos filtrar os eventos de cada calendário. Esses dois campos serão preenchidos automaticamente, através dos dados do login do usuário, portanto ficam transparentes durante a manutenção dos eventos
* local : podemos criar um cadastro de locais, e aí sim, na hora de cadastrar um evento, essa lista é carregada para que o usuário escolha o local apropriado.
* em relação à descrição, penso que esta é a concatenação de todos os outros campos, e seria mostrada ao usuário no momento que o mesmo clica no evento.

Esse é o funcionamento padrão do componente de calendário disponível; ele pode ser customizado até certo ponto facilmente. Caso precisemos de algo que saia muito do padrão, aí sim teríamos que alterar o componente, o que não é uma boa prática, mas em último caso, possível.

Esta semana vamos disponibilizar um link com o componente para que vocês possam navegar no mesmo, e aí vamos amadurecendo mais a idéia.

**Comment by Ebianca** [comment]
Ok

**Comment by Ebianca** [comment]
Ok

**Comment by aleodoni** [comment]
Vou fechar essa issue. Caso alterações sejam necessárias, criaremos uma nova.
