### ISSUE TITLE
Teste plugin calendar

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/calendario#2]
Testar o plugin de calendário (https://github.com/Serhioromano/bootstrap-calendar)

Criar a página que receba a info em formato JSON do serviço fake com as informações para teste.
Formatação inicial português/brasil
Disponibilizar tela para validação do usuário

**Comment by edersoncosta** [comment]
Apenas para mostrar que estou logado no git

**Comment by aleodoni** [comment]
vou fechar essa issue. tela já criada.
