### ISSUE TITLE
Configuração servidor staging

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/calendario#28]
@brunosoli, vou precisar adicionar este projeto no staging, e preciso de sua ajuda para :

* Verificar se os certificados SSL continuam os mesmos (/etc/ssl/certs/cmc/201603-201903/cmc.pr.gov.br.crt e /etc/ssl/private/cmc/201603-201903/cmc.pr.gov.br.key)
* Criar um nome para acesso do projeto, tipo : calendario.staging.cmc.pr.gov.br

**Comment by brunosoli** [comment]
O certificado é válido até março de 2019.
Os nomes foram adicionados no DNS:
calendario.cmc.pr.gov.br e
calendario.staging.cmc.pr.gov.br
