### ISSUE TITLE
Arredondar layout página calendário

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/calendario#56]
# Descrição
Formatar o layout desta página
https://calendario.staging.cmc.pr.gov.br/calendario/

## Requisito 1
Retirar texto "Teste Calendário"

## Requisito 2
Mudar texto dos botões para português

Pessoal (@diemello, @Ebianca, @edersoncosta), por favor adicionem sugestões de layout nesta tela. Para tanto, criem mais requisitos nesta issue.

**Comment by Ebianca** [comment]
Dei uma olhada no layout, mas não consegui pensar em sugestões ainda. Até sexta verifico. 
A princípio esse modelo de visão mês, onde aparece a bolinha colorida, seria ideal aparecer como no modelo semanal, já com o nome do evento.

**Comment by aleodoni** [comment]
Ok, @Ebianca, @edersoncosta, @diemello  apenas a questão dos nomes do evento ao invés da bolinha (na visão mensal), teríamos que alterar o código fonte do componente calendário. É possível, mas tem alguns inconvenientes : 
1. Demanda um tempo bem maior, pois teríamos que estudar e alterar este código-fonte;
2. Perdemos a possibilidade de atualização do componente, uma vez que implementamos alterações no mesmo.

**Comment by edersoncosta** [comment]
@aleodoni @Ebianca @diemello Bom, acredito que não precisamos deixar iniciado pelo mês e sim trazer a tela na semana, no mês na minha opinião pode continuar a bolinha, pois o que interessa para as pessoas que irão visualizar a tela é apenas a agenda da semana e essa está vindo corretamente descrita. Também podemos apresentar uma palestra de orientação do calendário e uso se for necessário e conveniente.

**Comment by aleodoni** [comment]
Pessoal, vou fechar essa issue e caso alguma modificação seja necessária, vamos criar uma nova issue para ela.

**Comment by diemello** [comment]
Melhor não alterar o componente original, mantendo as atualizações futuras, e iniciando na tela de semana onde existe a descrição resolve o problema

**Comment by Ebianca** [comment]
@aleodoni  @diemello @edersoncosta Vou responder aqui mesmo, se precisar copio em outra que você abrir.

Nas conversas iniciais reforçamos que precisamos de algo "igual" ao google calendário. Conversei novamente com a Jussana e precisamos que seja o layout Mês com a descrição do evento, não a bolinha. Tendo em vista, ainda, que será utilizada futuramento por toda a Câmara,  deve aparecer da seguinte forma:

Hora e Evento
8:00 Comissão Economia

Não vejo possibilidade em manter desse jeito do modelo que nos passaram com a bolinha, porque o acesso será feito por pessoas de todos os tipos, incluindo a sociedade para acompanhamento de eventos, não sendo possível realizar treinamentos ou utilizar layouts que não sejam fáceis de visualizar. 

Dúvidas estamos à disposição.

**Comment by aleodoni** [comment]
Da minha parte, sem problemas, contanto que todos fiquem cientes e concordem com os pontos que citei anteriormente.

**Comment by aleodoni** [comment]
Abri uma issue nova que especifica estas mudanças :  #62, portanto vou fechar esta.
