### ISSUE TITLE
Fim de semana e Feriado

### ISSUE THREAD

**Issue by Ebianca** [CMCuritiba/calendario#63]
@aleodoni @edersoncosta @brunosoli Favor verificar as seguintes possibilidades.

1) Feriados estão aparecendo no calandário apenas com a cor da data diferente, habilitar para aparecer o texto por extenso.

2) Ao invés de colocar os comunicados apenas como link, ver a possbilidade de ocultar a coluna de fim de semana, condicionada a aparecer somente se tiver algum evento, que é raro (ex. Dia de eleição), semelhante à imagem anexa.

![captura de tela em 2018-07-02 15-10-32](https://user-images.githubusercontent.com/40066179/42179387-29f5a4ce-7e0a-11e8-8a2d-f629143c8c27.png)

2)1- Ou Diminuir o layout do campo, para que fiquem colunas pequenas.

**Comment by aleodoni** [comment]
Em relação aos feriados, a melhor opção seria cadastra-los no banco de dados. Isso pode ser feito manualmente (de início - e depois verificarmos uma maneira de fazer isso de maneira mais automática).
Em relação aos finais de semana, por enquanto foram omitidas estas colunas. Se realmente for necessário, podemos implementar uma condicional para mostrar estas colunas caso exista algum evento cadastrado.
Vou fechar essa issue. Depois criamos novas issues separadas para cada caso.
