### ISSUE TITLE
Validações cosméticas/funcionais para Calendário, Comunicados Gerais e Cronograma Comissões

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/calendario#77]
Pessoal, está disponível uma nova versão do calendário no endereço : https://calendario.staging.cmc.pr.gov.br/calendario/full
Por favor verifiquem o funcionamento do mesmo e coloquem as ponderações nesta issue para que possamos refiná-las.

**Comment by Ebianca** [comment]
@aleodoni  Ficou bem melhor o layout. Ainda acho que o quadro de comunicados deve ficar em destaque, ao lado do calendário, ao invés de ser um item expansivel. Veja que na imagem abaixo não fica muito pequena a agenda com a coluna na esquerda.

- Seria interessante também, se possível, uma cor de fundo diferente de branco, mesmo que seja um cinza claro (sugestão jussana).

- Outro ponto, tem como abrir os detalhes do evento sem abrir uma nova aba? Assim como no google? Ver imagem abaixo, ele não abre outra página e sim o detalhamento.

![captura de tela em 2018-07-10 14-16-08](https://user-images.githubusercontent.com/40066179/42526335-e6ccd2ba-844b-11e8-8605-3b56e3b6bf9c.png)

**Comment by aleodoni** [comment]
### Mudanças efetuadas : 
1. Mudança da cor de fundo. De branco para cinza claro;
2. Botões fixos para cada quadro (Calendário, Comunicados Gerais e Cronograma das Comissões). Assim, fica mais visível as opções disponíveis para o usuário.
3. Adicionada visualização de semana para o calendário.
4. Adicionado cabeçalho com logo da CMC
Essas são as alterações mais imediatas que puderam ser feitas hoje. As demais que foram conversadas na reunião, abrirei uma issue para cada.
