### ISSUE TITLE
Layout Temporário Agenda

### ISSUE THREAD

**Issue by Ebianca** [CMCuritiba/calendario#80]
@aleodoni @edersoncosta 
Conversei com a Jussana e ela topou divulgar, quando retornar, o layout alternativo até que fique da forma como precisamos.

Sendo assim, o ideal é colocar 3 botões  lado a lado, semelhante que vimos no site da samsung, obrigando o usuário a selecionar para abrir a agenda, os comunicados e o cronograma, ao invés de liks em linha.

**Comment by aleodoni** [comment]
@Ebianca, acredito que o layout novo contempla esse requisito. Vou fechar a issue.
