### ISSUE TITLE
Acesso para cadastro de eventos

### ISSUE THREAD

**Issue by Ebianca** [CMCuritiba/calendario#81]
@aleodoni  aguardo link para acesso ao cadastro de eventos para testar e repassar para Deborah que será a responsável por esse cadastro quando da conclusão da agenda.

**Comment by aleodoni** [comment]
@Ebianca, segue o link : https://calendario.staging.cmc.pr.gov.br/calendario/evento/

**Comment by Ebianca** [comment]
ok. Acessado.

**Comment by Ebianca** [comment]
Liberar também Acesso para Débora, ela já logou para registrar.
