### ISSUE TITLE
Alterações layout calendário/comunicados

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/calendario#83]
# Descrição
Opção para mostrar os comunicados ao lado do calendário
## Informações Técnicas
Utilizar formatação condicional para pelo menos 2 dispositivos (desktop e tablet)

**Comment by Ebianca** [comment]
@aleodoni @edersoncosta 
Alterações após testes de cadastro:

Campo evento na agenda possuir cor e negrito na fonte e não cor no fundo do campo no fundo.

![image](https://user-images.githubusercontent.com/40066179/42652336-7aa06b44-85e8-11e8-8074-748a45221420.png)

Finalidade do Campo Ativo/Inativo? Caso a reunião seja cancelada era continuará na agenda, com o Status cancelada, mas deve continuar aparecendo na agenda. Pode até gerar uma incormação antes da descrição ECONOMIA quando ativa > CANCELADA - ECONOMIA quando cancelada se mudar o staus de ativo  inativo. Ao menso entendi assim a função desse campo.


Dúvida: Como edito novamente um evento alterado para Inativo? fiz isso como teste e o evento não aparece mais na lista de eventos.

**Comment by aleodoni** [comment]
@Ebianca @edersoncosta @diemello 
Pelo que entendi no comentário anterior, devemos retirar as cores de fundo dos eventos, correto? Hoje eles estão assim : 

![screenshot at 2018-08-20 11 22 25](https://user-images.githubusercontent.com/12944198/44346111-8be07880-a46b-11e8-864a-ac3f210cb376.png)

Essas cores de fundo são definidas no cadastro do evento quando você seleciona a classe do mesmo. 
Vou alterar a classe então para eliminar a cor de fundo e alterar a cor da fonte, ok? Para isso abrirei uma nova issue específica para isso.

Em relação ao campo Ativo/Inativo, vou criar um novo status de CANCELADO para que o mesmo continue a aparecer na agenda, mas com este status. Hoje, os eventos inativos não aparecem na agenda.

Em relação à sua dúvida, o campo só aparecerá novamente na agenda se o status dele for ATIVO (e agora também CANCELADO). Vou criar uma issue separada para esta alteração também.

**Comment by aleodoni** [comment]
@Ebianca @edersoncosta @diemello 
Quando puder, acessem https://calendario.staging.cmc.pr.gov.br/calendario/full_botao para validar as alterações feitas nessa issue. Fico no aguardo para fechar ou corrigir alguma coisa.

**Comment by Ebianca** [comment]
@aleodoni Testes realizados. 
Considerações: 1)  quando altero o evento para status cancelado ele não aparece mais na tela de cadastro de eventos. Fica melhor continuar aparecendo.

![image](https://user-images.githubusercontent.com/40066179/44582621-95722500-a778-11e8-9ad9-8edf204e4e5d.png)


![image](https://user-images.githubusercontent.com/40066179/44582601-855a4580-a778-11e8-9b0b-0de9d9ad9e76.png)

2) Não entendi a ideia de cadastro do feriado, porque mesmo selecionando esta classe ele pede dia e hora do evento, veja como ficou na agenda. Da mesma forma, notei que ao selecionar classes diferentes de "Nulo" não muda nada no evento. Era pra mudar?

Do mais tudo ok, está ficando muito boa.

Aguardo acesso para manutenção da tela de Cronograma, para verificar como serão feitas as alterações.

**Comment by Ebianca** [comment]
@aleodoni 
1)Ficou melhor o cancelado na frente, não precisa mudar. A questão é que na lista de eventos cadastrados (não na agenda) o status cancelado não aparece para possíveis alterações, só aparecem os ativos.

2)Quanto as classes dá pra manter assim, não precisa retirar do sistema. A dúvida é como cadastrar o feriado para que ele entenda que é no dia e não no horário, estilo google.

![image](https://user-images.githubusercontent.com/40066179/44600504-d9345100-a7af-11e8-9032-bf706c2dd428.png)


3)Sobre o cronograma realmente é dificil acontecer alteração, mas o cacá saiu de licença e entrou o Chicarelli, e uma reunião mudou de horário padrão em função da utilização das salas das comissões (para não serem concomitantes). Se vocês não se importam de alterar quando precisar, tudo bem.

**Comment by Ebianca** [comment]
@aleodoni  Alteração no cronograma: Participação Legislativa - substituir cacá pereira por chicarelli;
acessibilidade - Horário reunião segunda 08:45 ao invés de 8:30.

Passei para o Ederson uma correção de layout quando muda a visualiação de mensal para semanal, ou quando muda o mês. Os espaços dos dias aumentam e gera barra de rolagem, quando deveria ficar tudo na mesma tela. Ex. abaixo.

**Inicial**

![image](https://user-images.githubusercontent.com/40066179/45088477-78761400-b0df-11e8-9faf-6955ab372597.png)

**Mudando o mês**

![image](https://user-images.githubusercontent.com/40066179/45088509-92175b80-b0df-11e8-9578-50ad5bb4a786.png)


Do mais tudo ok, as outras correções que abrirá/abriu issue não interferem na divulgação da agenda.

**Comment by aleodoni** [comment]
@Ebianca @edersoncosta vou verificar se isso não é comportamento do componente tentando ajustar a responsividade.

**Comment by aleodoni** [comment]
Vou abrir uma nova issue para a questão do layout mensal/semanal. As outras alterações estão feitas. Vou fechar essa issue.
